-- generated by `arc psqldb migrate` for plugin 'mail'

-- (schema) ensure audit table "_audit_mail" exists

        CREATE TABLE IF NOT EXISTS "_audit_mail" (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            "table"     TEXT NOT NULL,
            row_id      UUID NOT NULL,
            changes     JSONB NOT NULL,
            changed_by  UUID,
            changed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        ;

        CREATE OR REPLACE FUNCTION arc_audit_mail() RETURNS trigger AS $$
        DECLARE
            new_json jsonb := to_jsonb(NEW);
            old_json jsonb := to_jsonb(OLD);
        BEGIN
            -- changed_by goes through the jsonb representation, not a direct
            -- NEW.updated_by/OLD.updated_by struct reference: this function is
            -- shared across every audited table for the plugin, and a
            -- "system": true table (psqldb.model) self-declares its own
            -- columns — it has no auto-injected updated_by at all. ->>'key' on
            -- jsonb degrades to NULL when the key's absent instead of raising
            -- "record has no field", so this works for both table shapes
            -- without the function needing to know which one it's on.
            INSERT INTO "_audit_mail" ("table", row_id, changes, changed_by)
            VALUES (
                TG_TABLE_NAME,
                COALESCE(NEW.id, OLD.id),
                jsonb_build_object(
                    'before', CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE old_json END,
                    'after',  CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE new_json END
                ),
                COALESCE((new_json->>'updated_by')::uuid, (old_json->>'updated_by')::uuid)
            );
            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql
        ;

-- (schema) CREATE TABLE "mailaccount" (14 fields)
CREATE TABLE IF NOT EXISTS "mailaccount" (
    "id" UUID PRIMARY KEY DEFAULT arc_uuid_generate_v7(),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "created_by" UUID,
    "updated_by" UUID,
    "_state" INTEGER NOT NULL DEFAULT 0,
    "name" VARCHAR(60) NOT NULL UNIQUE,
    "provider" VARCHAR(255) NOT NULL DEFAULT 'smtp',
    "from_email" VARCHAR(255) NOT NULL,
    "from_name" VARCHAR(120),
    "config" JSONB,
    "secret_ref" VARCHAR(120),
    "is_default" BOOLEAN NOT NULL DEFAULT FALSE,
    "enabled" BOOLEAN NOT NULL DEFAULT TRUE
);
DROP TRIGGER IF EXISTS arc_set_updated_at ON "mailaccount";
CREATE TRIGGER arc_set_updated_at BEFORE UPDATE ON "mailaccount" FOR EACH ROW EXECUTE FUNCTION arc_set_updated_at();
DROP TRIGGER IF EXISTS arc_soft_delete_to_trash ON "mailaccount";
CREATE TRIGGER arc_soft_delete_to_trash AFTER INSERT OR UPDATE ON "mailaccount" FOR EACH ROW EXECUTE FUNCTION arc_soft_delete_to_trash();

-- (schema) mailaccount: attach audit trigger
DROP TRIGGER IF EXISTS arc_audit_mail ON "mailaccount";
CREATE TRIGGER arc_audit_mail AFTER INSERT OR UPDATE OR DELETE ON "mailaccount" FOR EACH ROW EXECUTE FUNCTION arc_audit_mail();

-- (schema) CREATE TABLE "mailtemplate" (11 fields)
CREATE TABLE IF NOT EXISTS "mailtemplate" (
    "id" UUID PRIMARY KEY DEFAULT arc_uuid_generate_v7(),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "created_by" UUID,
    "updated_by" UUID,
    "_state" INTEGER NOT NULL DEFAULT 0,
    "name" VARCHAR(80) NOT NULL UNIQUE,
    "subject" VARCHAR(200) NOT NULL,
    "text_body" TEXT NOT NULL,
    "html_body" TEXT,
    "sample_context" JSONB
);
DROP TRIGGER IF EXISTS arc_set_updated_at ON "mailtemplate";
CREATE TRIGGER arc_set_updated_at BEFORE UPDATE ON "mailtemplate" FOR EACH ROW EXECUTE FUNCTION arc_set_updated_at();
DROP TRIGGER IF EXISTS arc_soft_delete_to_trash ON "mailtemplate";
CREATE TRIGGER arc_soft_delete_to_trash AFTER INSERT OR UPDATE ON "mailtemplate" FOR EACH ROW EXECUTE FUNCTION arc_soft_delete_to_trash();

-- (schema) mailtemplate: attach audit trigger
DROP TRIGGER IF EXISTS arc_audit_mail ON "mailtemplate";
CREATE TRIGGER arc_audit_mail AFTER INSERT OR UPDATE OR DELETE ON "mailtemplate" FOR EACH ROW EXECUTE FUNCTION arc_audit_mail();
