-- generated by `arc psqldb migrate` for plugin 'mail'

-- (schema) ensure audit table "_audit_mail" exists

        CREATE TABLE IF NOT EXISTS "_audit_mail" (
            id          UUID PRIMARY KEY DEFAULT arc_uuid_generate_v7(),
            "table"     TEXT NOT NULL,
            row_id      UUID NOT NULL,
            changes     JSONB NOT NULL,
            changed_by  TEXT,
            changed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        ;

        CREATE OR REPLACE FUNCTION arc_audit_mail() RETURNS trigger AS $$
        DECLARE
            new_json jsonb := to_jsonb(NEW);
            old_json jsonb := to_jsonb(OLD);
        BEGIN
            -- changed_by goes through the jsonb representation, not a direct
            -- NEW.updated_by/OLD.updated_by struct reference: this function is
            -- shared across every audited table for the plugin, and a
            -- "system": true table (psqldb.model) self-declares its own
            -- columns — it has no auto-injected updated_by at all. ->>'key' on
            -- jsonb degrades to NULL when the key's absent instead of raising
            -- "record has no field", so this works for both table shapes
            -- without the function needing to know which one it's on.
            INSERT INTO "_audit_mail" ("table", row_id, changes, changed_by)
            VALUES (
                TG_TABLE_NAME,
                COALESCE(NEW.id, OLD.id),
                jsonb_build_object(
                    'before', CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE old_json END,
                    'after',  CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE new_json END
                ),
                COALESCE(new_json->>'updated_by', old_json->>'updated_by')
            );
            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql
        ;

-- (schema) mailaccount: attach audit trigger
DROP TRIGGER IF EXISTS arc_audit_mail ON "mailaccount";
CREATE TRIGGER arc_audit_mail AFTER INSERT OR UPDATE OR DELETE ON "mailaccount" FOR EACH ROW EXECUTE FUNCTION arc_audit_mail();

-- (schema) mailtemplate: attach audit trigger
DROP TRIGGER IF EXISTS arc_audit_mail ON "mailtemplate";
CREATE TRIGGER arc_audit_mail AFTER INSERT OR UPDATE OR DELETE ON "mailtemplate" FOR EACH ROW EXECUTE FUNCTION arc_audit_mail();
